services:
  # Backend API
  - type: web
    name: water-sort-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false

  # Frontend
  - type: web
    name: water-sort-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
